dist: trusty
sudo: required
language: node_js
before_install:
- sudo chown root:$USER /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
install:
- npm install
node_js:
- 'node'
script:
- npm run build
- npm run test
- cat ./coverage/lcov.info | coveralls
cache:
  directories:
  - node_modules
